{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nl-portal-backend.fullname" . }}
  labels:
    {{- include "nl-portal-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.settings.database.password | toString | b64enc | quote }}
  NLPORTAL_ZGW_CATALOGIAPI_CLIENTID: {{ .Values.settings.nlPortal.zgw.catalogiapi.clientId | toString | b64enc | quote }}
  NLPORTAL_ZGW_CATALOGIAPI_SECRET: {{ .Values.settings.nlPortal.zgw.catalogiapi.secret | toString | b64enc | quote }}
  NLPORTAL_ZGW_DOCUMENTAPI_CLIENTID: {{ .Values.settings.nlPortal.zgw.documentenapi.clientId | toString | b64enc | quote }}
  NLPORTAL_ZGW_DOCUMENTAPI_SECRET: {{ .Values.settings.nlPortal.zgw.documentenapi.secret | toString | b64enc | quote }}
  NLPORTAL_ZGW_ZAKENAPI_CLIENTID: {{ .Values.settings.nlPortal.zgw.zakenapi.clientId | toString | b64enc | quote }}
  NLPORTAL_ZGW_ZAKENAPI_SECRET: {{ .Values.settings.nlPortal.zgw.zakenapi.secret | toString | b64enc | quote }}
  NLPORTAL_ZGW_OBJECTENAPI_TOKEN: {{ .Values.settings.nlPortal.zgw.objectenapi.token | toString | b64enc | quote }}
  NLPORTAL_ZGW_KLANTENAPI_CLIENTID: {{ .Values.settings.nlPortal.zgw.klantenapi.clientId | toString | b64enc | quote }}
  NLPORTAL_ZGW_KLANTENAPI_SECRET: {{ .Values.settings.nlPortal.zgw.klantenapi.secret | toString | b64enc | quote }}
{{- end }}