# Default values for valtimo-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tags:
  # -- Deploy a PostgreSQL instance
  postgresql: false
  # -- Deploy a MySQL instance
  mysql: false
  # -- Deploy a Keycloak instance
  keycloak: false

# -- Amount of replicas running the Valtimo-backend
replicaCount: 1

image:
  # -- Domain of the image repository
  repository: "ghcr.io/valtimo-platform/apaas-valtimo-backend"
  # -- Pull policy for the image
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "main-01af98c8"

# -- Image pull secrets
imagePullSecrets:
  - name: ghcr
# -- Name override for Valtimo-Backend
nameOverride: ""
# -- String to fully override valitmo-backend.fullname
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for Valtimo-backend pods
podAnnotations: {}

# -- Labels for Valtimo-backend pods
podLabels: {}

podSecurityContext: 
  # -- Set Valtimo-backend's pod security fsGroup
  fsGroup: 2000

securityContext: 
  capabilities:
    # -- Valtimo-backend's container security context capabilities to be dropped
    drop:
    - ALL
  # -- Valtimo-backend's container security context readOnlyRootFilesystem
  readOnlyRootFilesystem: false
  # -- Run Valtimo-backend containers as non-root
  runAsNonRoot: true
  # -- Run Valtimo-backend containers under this user-ID
  runAsUser: 1000

service:
  # -- Valtimo-backend service type
  type: ClusterIP
  # -- Valtimo-backend service port
  port: 80

ingress:
  # -- Expose the Valtimo-backend UI through an ingress
  enabled: true
  # -- Ingress Class which will be used to implement the Ingress
  className: "alb"
  # -- Ingress annotations
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:647007154019:certificate/c1a53b7a-b477-42b0-870a-ef7454321314
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.name: "nonprod"
  hosts: 
    - host: apaas-test.firstcustomer.aws-playground.ritense.com
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: valtimo-backend
              port:
                number: 8080
  # -- Enable TLS for the Ingress
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

livenessProbe:
  # -- Initial delay seconds for livenessProbe
  initialDelaySeconds: 40
  # -- Period seconds for livenessProbe
  periodSeconds: 10
  # -- Timeout seconds for livenessProbe
  timeoutSeconds: 1
  # -- Failure threshold for livenessProbe
  failureThreshold: 6
  # -- Success threshold for livenessProbe
  successThreshold: 1

readinessProbe:
  # -- Initial delay seconds for readinessProbe
  initialDelaySeconds: 20
  # -- Period seconds for readinessProbe
  periodSeconds: 10
  # -- Timeout seconds for readinessProbe
  timeoutSeconds: 1
  # -- Failure threshold for readinessProbe
  failureThreshold: 6
  # -- Success threshold for readinessProbe
  successThreshold: 1

# -- Resources for Valtimo-backend
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  # -- Enable/disable autoscaling for the Valtimo-backend deployment
  enabled: false
  # -- Minimum replicas for the Valtimo-backend deployment
  minReplicas: 1
  # -- Maximum replicas for the Valtimo-backend deployment
  maxReplicas: 100
  # -- Valtimo-backend Deployment autoscaling target CPU percentage
  targetCPUUtilizationPercentage: 80
  # -- Valtimo-backend Deployment autoscaling target Mem utilization percentage
  targetMemoryUtilizationPercentage: 80

# -- Node labels for Valtimo-backend pods assignment
nodeSelector: {}

# -- Tolerations for Valtimo-backend pods assignment
tolerations: []

# -- Affinity for Valtimo-backend pods assignment 
affinity: {}

# -- Refer to an existing secret to avoid managing secrets through Helm.
existingSecret: null

settings:

  spring: 
    profiles:
      # -- Activated Spring profiles
      active: "cloud"
    actuator: 
      # -- Username to access the Spring actuator endpoint
      username: "admin"
      # -- Password to access the Spring actuator endpoint
      password: ""
    datasource: 
      # -- URL for the database
      url: jdbc:postgresql://firstcustomerfifthtry-rdsstack-1vkyzbi6fmey4-dbinstance.cuvfsxm0m5wp.eu-west-1.rds.amazonaws.com:3306/firstcustomertest
      # -- Username for the database
      username: firstcustomertest
      # -- Password for the database
      password: "JB_8x.ru.9XF!n.P"
    
  keycloak: 
    # -- URL of Keycloak
    authServerURL: https://apaas-keycloak.firstcustomer.aws-playground.ritense.com/auth
    # -- Keycloak realm
    realm: firstclient-nonprod
    # -- Client-ID to connect with Keycloak
    clientID: valtimo-firstclient-nonprod-m2m-client
    # -- Client-Secret to connect with Keycloak
    clientSecret: "g3nqVA64nw4gAYoq5tYYTfb0M4AUENbs"
    # -- Keycloak's Public Key used to verify signature of JWTs
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvcnrYkBwoW7hq9CaeDsHwCFQqhQkgAKbQ2qd4IMAjQBVf5Dtm79beYpSJMPETu/y7Yo/cVikyEw0D95U/usnawj+PrmWLPBmymUv4EhOQrH1qt6tXpUhohq8msVJkONIqq+1/TJN/oH+X1/XkgGhoPE+/weoJWBuybUPKEJxwxWeE7miojEGXcVFqLvxFRp3hGQfHIIX8EjEFoMMxGzbRz5jC9QXnO3Gatd45XtOrflUQyffEXlGsAFG3IEt40m7clpUNIxk0ggx7mw2QMePdLSMpoHIdHdVJ3cJv71ORKMu0Abr4UdQoKDZeWp1oEMGvwLsdlYLvlD7SnQhMUt8+QIDAQAB

  valtimo: 
    # -- Type of database to use (can by either 'postgres' or 'mysql')
    databaseType: "postgres"
    # -- The hostname which exposes Valtimo-backend
    appHostName: 
    # -- The port on which Valtimo-backend is listening
    serverPort: 8080
    # -- Encryption secret
    connectorEncryptionSecret: "0123456789101112"

  camunda: 
    # -- Default Camunda admin user
    adminUserID: "admin"
    # -- Default Camunda admin password
    adminUserPassword: "whatever"

##########################################################################
## PostgreSQL subchart                                                  ##
## https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values ##
##########################################################################
# -- Postgresql subchart by Bitnami. See https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values for all possible values
postgresql:

########################################################################
## MySQL subchart                                                     ##
## https://artifacthub.io/packages/helm/bitnami/mysql?modal=values    ##
########################################################################
# -- MySQL subchart by Bitnami. See https://artifacthub.io/packages/helm/bitnami/mysql?modal=values for all possible values
mysql:

########################################################################
## Keycloak subchart                                                  ##
## https://artifacthub.io/packages/helm/bitnami/keycloak?modal=values ##
########################################################################
# -- Keycloak subchart by Bitnami. See https://artifacthub.io/packages/helm/bitnami/keycloak?modal=values for all possible values
keycloak: 
