name: Build and Publish Helm Chart

on:
  workflow_dispatch:
    inputs:
      chartVersion:
        description: 'Chart Version'
        required: true

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  HELM_VERSION_TO_INSTALL: 3.5.0 # version of HEL to install
  GITHUB_CONTAINER_REGISTRY: ghcr.io/valtimo-platform

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: Generate helm index file for Valtimo Backend
        run: |
          helm repo index charts/valtimo-backend 

      - name: Generate helm index file for Valtimo Frontend
        run: |
          helm repo index charts/valtimo-frontend 

      - name: Save Valtimo Backend helm chart to local registry
        run: |
          tree .
          helm chart save charts/valtimo-backend ${{ env.GITHUB_CONTAINER_REGISTRY }}/chart-valtimo-backend:${{ github.event.inputs.chartVersion }}

      - name: Save Valtimo Frontend helm chart to local registry
        run: |
          helm chart save charts/valtimo-frontend ${{ env.GITHUB_CONTAINER_REGISTRY }}/chart-valtimo-frontend:${{ github.event.inputs.chartVersion }}

      - name: login to acr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GITHUB_CONTAINER_REGISTRY }} --username ${{ github.actor }} --password-stdin

      - name: Build Valtimo Backend Helm Chart
        run: |
          helm chart push ${{ env.GITHUB_CONTAINER_REGISTRY }}/chart-valtimo-backend:${{ github.event.inputs.chartVersion }}
      
      - name: Build Valtimo Frontend Helm Chart
        run: |
          helm chart push ${{ env.GITHUB_CONTAINER_REGISTRY }}/chart-valtimo-frontend:${{ github.event.inputs.chartVersion }}
